import type { Release } from '../types'

/**
 * Illustrative SAMPLE data — used as a fallback when the live JSON
 * (public/releases.json generated by scripts/refresh-news.mjs) cannot be
 * fetched. Keep this in sync with src/types.ts so it exercises all fields,
 * including the newest ones (image, Hugging Face lab).
 *
 * Figures below are placeholders for layout purposes, not verified facts.
 */
export const releases: Release[] = [
  {
    id: 'anthropic-opus-4-8',
    lab: 'Anthropic',
    title: 'Claude Opus 4.8',
    summary:
      "Anthropic's most capable model yet — stronger agentic coding, longer autonomous task horizons, and improved tool use across long sessions.",
    date: '2026-06-20T14:00:00Z',
    category: 'model',
    url: 'https://www.anthropic.com/news',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop',
    contextWindow: '500K',
    priceInput: '$5.00 / M',
    priceOutput: '$25.00 / M',
    benchmark: 'SWE-bench Verified 79%',
    tags: ['frontier', 'coding', 'agents'],
  },
  {
    id: 'openai-gpt-5-2',
    lab: 'OpenAI',
    title: 'GPT-5.2',
    summary:
      'A faster, cheaper update to the GPT-5 line with improved reasoning, better instruction following, and a larger context window.',
    date: '2026-06-12T16:00:00Z',
    category: 'model',
    url: 'https://openai.com/news/',
    image: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&auto=format&fit=crop',
    contextWindow: '400K',
    priceInput: '$3.50 / M',
    priceOutput: '$14.00 / M',
    benchmark: 'GPQA Diamond 88%',
    tags: ['frontier', 'reasoning'],
  },
  {
    id: 'huggingface-smollm3',
    lab: 'Hugging Face',
    title: 'SmolLM3: Compact models that punch above their weight',
    summary:
      'Hugging Face releases SmolLM3, a family of small open-weight language models that rival larger closed models on key benchmarks, optimized for on-device and edge deployment.',
    date: '2026-06-10T10:00:00Z',
    category: 'model',
    url: 'https://huggingface.co/blog/smollm3',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop',
    contextWindow: '32K',
    benchmark: 'MMLU 72%',
    tags: ['open-weights', 'efficient', 'edge'],
  },
  {
    id: 'google-gemini-3-ultra',
    lab: 'Google DeepMind',
    title: 'Gemini 3 Ultra',
    summary:
      'Native multimodal model with a 2M-token context window and state-of-the-art performance on long-document and video understanding.',
    date: '2026-06-05T15:30:00Z',
    category: 'model',
    url: 'https://deepmind.google/',
    contextWindow: '2M',
    priceInput: '$4.00 / M',
    priceOutput: '$18.00 / M',
    benchmark: 'MMMU 84%',
    tags: ['frontier', 'multimodal'],
  },
  {
    id: 'meta-llama-4-1',
    lab: 'Meta',
    title: 'Llama 4.1 405B (open weights)',
    summary:
      'Meta releases updated open-weight models with a permissive license, improved multilingual coverage, and a stronger instruct variant.',
    date: '2026-05-28T17:00:00Z',
    category: 'model',
    url: 'https://ai.meta.com/',
    contextWindow: '256K',
    benchmark: 'MMLU-Pro 76%',
    tags: ['open-weights', 'multilingual'],
  },
  {
    id: 'huggingface-inference-providers',
    lab: 'Hugging Face',
    title: 'Inference Providers: one API, every open model',
    summary:
      'Hugging Face launches a unified Inference Providers hub, letting developers route requests to hundreds of open models across multiple cloud providers through a single SDK with no quota juggling.',
    date: '2026-05-20T09:00:00Z',
    category: 'api',
    url: 'https://huggingface.co/blog/inference-providers',
    tags: ['api', 'open-weights', 'developer'],
  },
  {
    id: 'anthropic-claude-code-2',
    lab: 'Anthropic',
    title: 'Claude Code 2.0',
    summary:
      'Agentic coding in the terminal gains subagents, background tasks, and reusable workflows for multi-step engineering work.',
    date: '2026-05-22T13:00:00Z',
    category: 'feature',
    url: 'https://www.anthropic.com/news',
    tags: ['developer', 'agents'],
  },
  {
    id: 'openai-realtime-ga',
    lab: 'OpenAI',
    title: 'Realtime API is now generally available',
    summary:
      'Low-latency speech-to-speech for production voice apps, with cheaper audio tokens and improved interruption handling.',
    date: '2026-05-15T18:00:00Z',
    category: 'api',
    url: 'https://openai.com/news/',
    tags: ['voice', 'api'],
  },
  {
    id: 'mistral-large-3',
    lab: 'Mistral',
    title: 'Mistral Large 3',
    summary:
      'A new European frontier model focused on efficiency and strong coding, available via API and for on-prem deployment.',
    date: '2026-05-09T10:00:00Z',
    category: 'model',
    url: 'https://mistral.ai/news/',
    contextWindow: '256K',
    priceInput: '$2.00 / M',
    priceOutput: '$6.00 / M',
    benchmark: 'HumanEval 90%',
    tags: ['frontier', 'efficient'],
  },
  {
    id: 'xai-grok-4',
    lab: 'xAI',
    title: 'Grok 4',
    summary:
      'xAI ships its next flagship with real-time data access and a larger reasoning budget for agentic tasks.',
    date: '2026-05-02T20:00:00Z',
    category: 'model',
    url: 'https://x.ai/',
    contextWindow: '256K',
    benchmark: 'AIME 92%',
    tags: ['frontier', 'realtime'],
  },
  {
    id: 'deepseek-v4',
    lab: 'DeepSeek',
    title: 'DeepSeek V4 (open)',
    summary:
      'A highly efficient open mixture-of-experts model that narrows the gap with closed frontier labs at a fraction of the cost.',
    date: '2026-04-24T09:00:00Z',
    category: 'model',
    url: 'https://www.deepseek.com/',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&auto=format&fit=crop',
    contextWindow: '128K',
    priceInput: '$0.27 / M',
    priceOutput: '$1.10 / M',
    benchmark: 'MATH 89%',
    tags: ['open-weights', 'moe', 'cheap'],
  },
  {
    id: 'anthropic-interpretability',
    lab: 'Anthropic',
    title: 'New interpretability research: tracing model thoughts',
    summary:
      'A paper introducing methods to trace internal features and circuits, improving transparency into how models reach answers.',
    date: '2026-04-10T12:00:00Z',
    category: 'research',
    url: 'https://www.anthropic.com/research',
    tags: ['safety', 'interpretability'],
  },
]
